load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "Collect",
    srcs = ["Collect.java"],
    visibility = ["//visibility:public"],
    deps = ["//src/main/java/com/funccover:CoverageMetrics"],
)
