name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Google Java Format
        uses: axel-op/googlejavaformat-action
